name: flutteer_teste
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  fluttertoast: ^4.0.1
  flutter:
    sdk: flutter

  cielo_ecommerce: ^0.1.2
  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  async: ^2.4.0
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true